### ISSUE TITLE
Producción -> Producción de Lotes:  El formulario permite ingresar cualquier código de lote pudiendo coincidir con un código ya existente

### ISSUE THREAD

**Issue by Nahuel1705** [Trazalog/traz-prod-trazasoft#10]
ID del bug: PRD-PRL-01-NA

Descripción: Cuando se va a crear una nueva etapa productiva el formulario permite ingresar cualquier codigo de lote pudiendo coincidir con un codigo ya existente. Si este es el caso cuando se quiera ver la trasabilidad de la etapa el codigo repetido solo traera la ultima etapa cargada con ese codigo.

El formulario deberia validar que el codigo ingresado no existe en la base de datos o generar este codigo automaticamente en todo caso.

Dos etapas que ya estaban cargadas tienen el mismo lote:
![image](https://user-images.githubusercontent.com/56811317/116742094-45d66380-a9cd-11eb-8ebc-9e4ea249d161.png)

La trazabilidad solo trae la mas nueva:
![image](https://user-images.githubusercontent.com/56811317/116742192-6b636d00-a9cd-11eb-9da0-152a8e936d17.png)

**Comment by aalfaro-trazalog** [comment]
6/12/21
Sigue sin funcionar correctamente

![Se repite lote](https://user-images.githubusercontent.com/87376576/144876256-21b26a91-e1f4-413e-8678-1106ad7f3cad.png)

![se repite lote pierde trazabilidad](https://user-images.githubusercontent.com/87376576/144876468-9a02d43f-aee5-4713-8b6f-7d04086250f3.png)

**Comment by floto-trazalog** [comment]
Se propone la solución en las siguientes Issues:

- https://github.com/Trazalog/traz-comp-almacenes/issues/36
- https://github.com/Trazalog/traz-prod-trazasoft/issues/120

**Comment by aalfaro-trazalog** [comment]
Se valido con @mauriper que si se puede repetir el código de lote, lo que no debe poder repetirse es el nro de batch.
