### ISSUE TITLE
Soporte AGAL --> Producción: los Remitos que vienen con cajones los muestra como BINS

### ISSUE THREAD

**Issue by aalfaro-trazalog** [Trazalog/traz-prod-trazasoft#107]
v 1.5.27.2

Descripción:
En un remito venian dos tipos de envases, cajones y bins.  En esa carga para el remito 2520 había que ingresar la cantidad de bins y de cajones que contenian ajo.  Pero el sistema agrupó y sumó como cantidad total de X cant en bins, sin hacer la distinción de los cajones.

**Comment by floto-trazalog** [comment]
Esto se soluciona creando artículos diferentes, puesto que cada artículo se guarda con la unidad de medida específica.
Por lo tanto, se crea un artículo con unidad de medida _Cajón_ y otro con Unidad de medida _Bins_.
