### ISSUE TITLE
Producción -> Producción de Lotes: Se duplican lotes y no valida el nombre de los códigos

### ISSUE THREAD

**Issue by aalfaro-trazalog** [Trazalog/traz-prod-trazasoft#110]
v1.5.27.3

Descripción:
Este bug se descubrió luego de la revisión de la issue https://github.com/Trazalog/traz-prod-trazasoft/issues/10 en la cuál señalaba que el sistema no válida que al crear una nueva etapa productiva, se ingrese un codigo de lote que pueda coincidir con uno ya existente. 

Además de es bug, al finalizar la tarea, sale un alert de error, pero cuando revisamos en Producción de Lotes vemos que aparece 2 veces. 

Asi como también está permitiendo usar el mismo código de lote para distintas etapas, en este caso el código PP003 se lo pudo cargar en una etapa de Preclasificado y Pesado&Etiquetado.

https://user-images.githubusercontent.com/87376576/144621339-d8ac53c1-ae9f-4de4-aa2f-90b8c14fdc1b.mp4

![image](https://user-images.githubusercontent.com/87376576/144622813-5156418e-65b6-4ffe-ab59-f51e7b075af6.png)

Pasos para reproducir:

1. En menú seleccionar Producción
2. Click en Producción de Lotes
3. Elegir un código de lote que este precargado y copiarlo
4. Seleccionar el boton en forma de "+", seleccionar la nueva etapa a crear
5. Pegar el código de lote en el campo "Código Lote:*"
6. Completar campos obligatorios
7. Click en Iniciar etapa

**Comment by smustafa-trazalog** [comment]
Ya no aparce el reporte de error. Pero sigue cargando articulos con el mismo lote

**Comment by gnicolia-trazalog** [comment]
En la V 2.2.17 se encuentran varios cambios en comparacion de la version mencionada.

![image](https://github.com/Trazalog/traz-prod-trazasoft/assets/146888657/ab9bdc1d-d831-4360-8e3a-d4a639791396)

Se puede observar en la imagen que se agrego la columna de " ID BATCH".
