### ISSUE TITLE
Soporte AGAL-->Logística-->Recepción MP: marca el campo incorrecto a completar y traducir aclaración

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-prod-trazasoft#131]
Ambiente Test1 - v1.5.32

**Descripción:**
Al dejar incompleto el campo "Patente" el sistema marca el campo "Transportista", lo cual es incorrecto puesto que está rellenado, lo correcto sería que indique el que falta ingresar.

**Sugerencia:** traducir la aclaración: _Please enter a value_ a _Por favor, introduzca un valor_

![KIKO](https://user-images.githubusercontent.com/88331456/147260271-55c402f4-3544-4ea6-b62e-35cbcd925a9c.png)

**Pasos a reproducir:**

1. En menú Logística
2. Dar clic en Entrada | Recepción
3. Clic en Recepción MP
4. Completar los campos

**Comment by smustafa-trazalog** [comment]
Sin resolver
![image](https://user-images.githubusercontent.com/98842352/157737346-e7769781-fb51-4111-a751-532d93494f4c.png)
