### ISSUE TITLE
Soporte AGAL-->Producción-->Producción de Lotes: al Gestionar Reporte Fraccionamiento agrega el artículo Barbecho por defecto 

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-prod-trazasoft#134]
V1.5.32

**Descripción:**
Al gestionar una etapa del Fraccionamiento el sistema agrega por defecto el artículo MP0006 en todas las etapas de Fraccionamiento, corresponde que figuren los que el usuario agrega manualmente

![R1](https://user-images.githubusercontent.com/88331456/147499711-2b5b88f4-8a6e-49f5-a85b-78217442c7c3.png)

**Pasos a Reproducir:**

1. En menú Producción, dar click en Producción de Lotes
2. Click en botón de acción Gestionar
3. Click en botón Reproducción Fraccionamiento

**Comment by aalfaro-trazalog** [comment]
Solucionado en v 1.5.34
