### ISSUE TITLE
Reportes-->Ingresos: se corta el campo Estado de la tabla

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-prod-trazasoft#136]
ambiente: Ramon Serrano - v1.5.32

**Descripción:**
En la pantalla de Reportes Ingresos se observa que la tabla corta la columna del campo "Estado"

![RepIng38](https://user-images.githubusercontent.com/88331456/147570618-e895f7af-18cb-479b-b5af-c1c87bf6428d.png)

**Pasos a reproducir:**

1. En Reportes click en Ingresos

**Comment by aalfaro-trazalog** [comment]
Solucionado en v 1.5.35
