### ISSUE TITLE
Producción-->Etapas Productivas-->Ver artículo: no tiene funcionalidad el buttom "Eliminar"

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-prod-trazasoft#138]
Ambiente: test - V1.5.32

**Descripción:**
Al eliminar un artículo de la etapa productiva el botón de acción está inhabilitado, entonces lo correcto sería que el sistema abra una ventana modal preguntando al usuario si realmente desea eliminar ese artículo con las opciones "Cancelar" y "Aceptar"

![ELIM](https://user-images.githubusercontent.com/88331456/147604337-e037faa0-6f51-4e90-958d-1d906880783a.png)

**Pasos a reproducir:**

1. En Producción dar click en Etapas Productivas
2. Click en botón "Agregar"
3. Posicionarse sobre algún artículo del listado
4. Dar click en el botón de acción "Eliminar"

**Comment by aalfaro-trazalog** [comment]
Solucionado en v 1.5.35

**Comment by floto-trazalog** [comment]
El ###BUG se repite en v2.0.13.6

**Comment by floto-trazalog** [comment]
Solucionado en v2.0.18
