### ISSUE TITLE
Soporte AGAL--->Producción-->Fraccionamiento: al Iniciar Etapa no muestra la unidad de medida del producto 

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-prod-trazasoft#140]
ambiente: test - v1.5.33

**Descripción:**
Al iniciar una nueva etapa de Fraccionamiento el campo de Stock no muestra la Unidad de Medida del Producto seleccionado, lo correcto sería que muestre la u. m. en este mismo campo para la tranquilidad del usuario

![UM](https://user-images.githubusercontent.com/88331456/147669246-4ee64141-269e-4dde-b5e9-0b4d36155f18.png)

**Pasos a reproducir:**

1. En Producción dar click en Producción de Lotes
2. Click en el botón **+** de la esquina superior derecha
3. Seleccionar Fraccionamiento
4. Completar los campos obligatorios

**Comment by aalfaro-trazalog** [comment]
Solucionado en v 1.5.34
