### ISSUE TITLE
Logística-->Entrada | Recepción-->Recepción MP: Indicar cuáles son los campos obligatorios que pide el modal

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-prod-trazasoft#147]
ambiente test - v1.5.33.1

**Descripción:**

Cuando se realiza la recepción de un camión y se omiten los datos del lote luego el sistema abre una modal para completar los campos obligatorios. Lo que corresponde es que se indiquen cuáles campos son los requeridos

https://user-images.githubusercontent.com/88331456/147785035-01789e83-2523-483f-b467-3adfcaab906f.mp4

**Pasos a reproducir:**

1. En Logística dar click en Entrada | Recepción
2. Dar click en Recepción MP
3. Completar los campos indicados como requeridos dejando los de _Ingreso_ y _Destino_ vacíos

**Comment by aalfaro-trazalog** [comment]
En v 1.5.34 sigue sin aparecer los campos marcados 
![image](https://user-images.githubusercontent.com/87376576/151559193-f0eed61e-9c46-472e-a14c-515c3cfadd15.png)

**Comment by aalfaro-trazalog** [comment]
Solucionado en v 1.5.35
