### ISSUE TITLE
Producción-->Producción de Lotes: al iniciar etapa de fraccionamiento no se indican los campos obligatorios

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-prod-trazasoft#148]
Ambiente Test - v1.5.33.1

**Sugerencia:**
Al dejar los campos de Detalles Fraccionamiento vacíos el sistema abre una modal de alerta para completar los campos obligatorios y en la pantalla no están indicados como tales, se recomienda agregar el ***** en los campos que sean requeridos

**Descripción:**
Al dejar vacío el campo _Producto_ y luego dar click en el botón Iniciar se abre una modal de alerta y, al insistir una 2da vez se abre una modal de Unificar Lotes (ver video)

https://user-images.githubusercontent.com/88331456/148257803-09b3bfd4-eaa0-460a-a55d-b9e54b10afc8.mp4

**Pasos a reproducir:**

1. En Producción dar click en Producción de Lotes
2. Click en el botón **+** (crear nueva etapa)
3. Seleccionar "Fraccionamiento"
4. Completar los campos obligatorios
5. Click en el botón "Agregar"
6. Click en el botón "Iniciar"

**Comment by smustafa-trazalog** [comment]
Sin resolver
![Uploading image.png…]()

ejemplo de campos obligatorios
![Group 1 (2)](https://user-images.githubusercontent.com/98842352/157744737-4b494d1c-2e9b-4267-829b-db8405235b34.png)

**Comment by aalfaro-trazalog** [comment]
Solucionado en v 2.1
