### ISSUE TITLE
Producción-->Producción de Lotes: el listado de etapas se corta a lo ancho y continúan abajo

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-prod-trazasoft#149]
Ambiente: test - v1.5.33.1

**Sugerencia:**
Se sugiere que el listado recorra el ancho de la pantalla como lo indica la imagen, teniendo en cuenta que si el último botón es largo pase directamente al escalón de abajo 

![PrdLot](https://user-images.githubusercontent.com/88331456/148586947-3d8c1f84-22e1-44a9-80d7-765c98826bbf.png)

**Pasos para reproducir**

1. En Producción dar click en Producción de Lotes

**Comment by aalfaro-trazalog** [comment]
Solucionado en v 1.5.35
