### ISSUE TITLE
Producción-->Producción de Lotes-->Gestionar: en el Reporte de Fraccionamiento no muestra el nombre del producto

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-prod-trazasoft#151]
Ambiente: empresa_de_prueba - v1.5.33.3

**Descripción:**
Al realizar el reporte de fraccionamiento y agregar el producto el sistema muestra un número en vez de mostrar el código del producto o nombre en su defecto. Al final se adjunta un ejemplo

![FRACC3](https://user-images.githubusercontent.com/88331456/149794466-57590462-68c7-4a80-926f-c185c797e709.png)

_El título subrayado en verde es el que debería figurar el nombre del producto en vez del número_
![FRACC2](https://user-images.githubusercontent.com/88331456/149799027-3a92dddc-a73a-4d6d-a210-a5ba76687adc.png)

**Pasos a reproducir:**

1. En Producción dar click en Producción de Lotes
2. Posicionarse sobre una etapa del tipo Fraccionamiento
3. Dar click en el botón de acción "Gestionar"
4. Dar click en el botón de "Reporte Fraccionamiento"
5. Completar los campos obligatorios
6. Dar click en el botón "Agregar"
7. Visualizar la tabla que figura en la parte de abajo

_Se adjunta un ejemplo de cómo debería figurar el nombre del producto_
![ADJ1](https://user-images.githubusercontent.com/88331456/149951667-d6769788-156b-440d-a57d-5513531259b5.png)

**Comment by aalfaro-trazalog** [comment]
Solucionado en v 1.5.34
