### ISSUE TITLE
Producción--> Prod de Lotes: alert de error incorrecto

### ISSUE THREAD

**Issue by aalfaro-trazalog** [Trazalog/traz-prod-trazasoft#155]
v 1.5.33.3

**Descripción:**
Si en bonita está caido, el sistema responde de manera aleatoria. Muestra alerts de error, cuando la tarea se ha iniciado correctamente. 

Nota: consultar con Rodo más detalles.

https://user-images.githubusercontent.com/87376576/150839004-fe42f6ad-8d4f-4a0a-a0dc-4affd10fd581.mp4

Pasos para reproducir:

1. En menú seleccionar Producción y click en Producción de Lotes 
2. Click en "Crear Nueva Etapa"
3. Seleccionar Finca
4. Cargar datos requeridos
5. Click en Iniciar Etapa

**Comment by floto-trazalog** [comment]
Solucionado antes de la v2.1.4.5
