### ISSUE TITLE
Producción--> Prod de Lotes: Agregar cabecera de datos de fraccionamiento

### ISSUE THREAD

**Issue by aalfaro-trazalog** [Trazalog/traz-prod-trazasoft#157]
v 1.5.33.3

**Descripción:**
Agregar  dos cabeceras desplegables (similar a la que se implemento en sicpoa), la primera "Infomacion de lotes" que va a traer los datos que se cargaron para el lote al momento de iniciar la etapa; mientras que la segunda "Información de Tarea" se correspondería lo cargado en producto fraccionado.

![image](https://user-images.githubusercontent.com/87376576/153902890-06e23a30-bec8-4c41-bf4b-98c6e11ac68e.png)

---------------------------------------------------------------------------------------------

1# Cabecera desplegada "Infomación de lotes"

![image](https://user-images.githubusercontent.com/87376576/153927632-62b8a9aa-db57-4cc7-ba24-994e4e0cf12e.png)

---------------------------------------------------------------------------------------------

2# Cabecera desplegada "Información de Tarea" 

![image](https://user-images.githubusercontent.com/87376576/153929041-2a70d6d5-d74a-4750-9bd5-063a97ffa40b.png)

---------------------------------------------------------------------------------------------

**Pasos para reproducir:**

1. En menú seleccionar Producción y click en Producción de Lotes
2. Seleccionar una etapa de tipo fraccionamiento
3. Click en Gestionar
4. Click en Reporte de Fraccionamiento

**Comment by floto-trazalog** [comment]
Se habló con Amalia y se llegó a la conclusión de cambiar las cabeceras por pestañas como en la modal de Pedidos Trabajo

![image](https://user-images.githubusercontent.com/88331456/154555543-5fb678ef-b1b0-43cf-9fda-92fc056d5950.png)

**Comment by smustafa-trazalog** [comment]
Sin resolver 

![Group 1 (3)](https://user-images.githubusercontent.com/98842352/157754330-dbad0527-68ac-4b10-995d-42af59b2a94d.png)
