### ISSUE TITLE
Producción de Lotes --> Gestionar: no funciona tomar tarea ni botón hecho

### ISSUE THREAD

**Issue by aalfaro-trazalog** [Trazalog/traz-prod-trazasoft#161]
v 1.5.34

**Descripción:**

No funciona tomar tarea ni botón hecho en la gestión de prod de lotes.

Desde la v 1.5.33.3 se perdió el cambio que realizo @KevinMarchan 
Anteriormente esto estaba solucionado, se había incluido el botón de finalizar pedido sin entrega (botón naranja) y el tomar tarea funcionaba.

https://user-images.githubusercontent.com/87376576/151567217-788b41a1-3cba-41a0-828d-3275571d47b2.mp4

**Comment by floto-trazalog** [comment]
Solucionado en v2.1.4.5
