### ISSUE TITLE
Producción de Lotes--> Nueva etapa: la fecha debe ser editable

### ISSUE THREAD

**Issue by aalfaro-trazalog** [Trazalog/traz-prod-trazasoft#163]
v 1.5.34

Descripción: 
Al iniciar una nueva etapa productiva, la fecha de alta debe ser editable (actualmente el sistema la muestra por defecto).

Sugerencia: habilitar el ícono de calendario para que el usuario pueda seleccionar la fecha.

![image](https://user-images.githubusercontent.com/87376576/152045013-04b042ea-12e5-403c-9d46-4eebbc70a2cd.png)

Pasos para reproducir:
1. En menú seleccionar Producción 
2. Click en producción de lotes
3. Click en Nueva etapa

**Comment by smustafa-trazalog** [comment]
v2.0.3
sin resolver
![image](https://user-images.githubusercontent.com/98842352/157953510-e4052908-515b-4ffc-bda9-c747f88e5d29.png)

**Comment by floto-trazalog** [comment]
Solucionado en v2.1.13.1
