### ISSUE TITLE
Logística: quitar los ABM Salida Camión y Descarga camión

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-prod-trazasoft#164]
Ambiente Test - v1.5.34

**Descripción:**
Se validó junto con Mauricio y Amalia quitar del módulo Logística las pestañas:

- Descarga Camión
- Salida Camión
puesto que para ejecutar esos movimientos se logra desde "Entrada | Recepción MP" y además se puede observar en la imagen que para el ambiente de Producción ya no figuran

![LGT-2](https://user-images.githubusercontent.com/88331456/152221857-4e1636da-7854-4748-9aff-d1fbca919793.png)

**Pasos para la reproducción:**

1. Dar click en el módulo Logística

**Comment by smustafa-trazalog** [comment]
sin resolver v2.0.3
![image](https://user-images.githubusercontent.com/98842352/157955402-339a251e-c27d-447f-acf0-76387c7f42f9.png)

**Comment by aalfaro-trazalog** [comment]
Solucionado v v2.0.13.6
