### ISSUE TITLE
Reporte--> Ingresos: Mantener fijo el titular de la tabla

### ISSUE THREAD

**Issue by aalfaro-trazalog** [Trazalog/traz-prod-trazasoft#168]
Actualizado
Se soluciono el bug que se corría el encabezado. 
### Agregar como mejora lo reportado en el comentario de abajo ⬇️

**Comment by smustafa-trazalog** [comment]
Ya no se superpone el encabezado, pero no aparece, esto se dificulta para la comprención de la tabla cuando se scrollea hacia abajo, ya que no se puede identificar el nombre de la columna.

https://user-images.githubusercontent.com/98842352/157962296-edfadb4d-8796-493b-87b4-004c9880551e.mp4

**Comment by floto-trazalog** [comment]
Solucionado antes de v2.1.4.5
