### ISSUE TITLE
Logística-->Entrada | Recepción: Resaltar botones de camiones

### ISSUE THREAD

**Issue by aalfaro-trazalog** [Trazalog/traz-prod-trazasoft#172]
v 1.5.35

**Descripción:**
La pantalla de Entrada | Recepción es poco intuitiva debido a que los iconos de los camiones, no indican que puedan ser presionados. Agregar estilo de hovering (que el fondo o los bordes se tornen celestes) sobre los botones de Entrada | Recepcion MP, para que el usuario logre identificar más rápido que se debe clickear dicho boton.

![image](https://user-images.githubusercontent.com/87376576/153437115-8aadb30e-1e87-4da8-8be6-d1e2ac0ce771.png)

**Pasos para reproducir:**

1. En menú seleccionar Logística
2. click en Entrada | Recepción MP

**Comment by smustafa-trazalog** [comment]
SIN RESOLVER
