### ISSUE TITLE
Producción-->ABM No Consumibles: no indica el Establecimiento y Recipiente en "Detalles" 

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-prod-trazasoft#173]
Ambiente Test - v1.5.36

**Descripción:**
Se sugiere agregar los campos "Establecimiento" y "Depósito" los cuales son datos importantes del No Consumible para el usuario a la hora de una búsqueda rápida

![BUG-1333](https://user-images.githubusercontent.com/88331456/153631076-65eb6532-9961-4565-8b76-36a3428362fb.png)

**Pasos para reproducir:**

1. En el menú Producción
2. Dar click en ABM No Consumibles
3. Dar click en el botón de acción "Ver detalles"

**Comment by aalfaro-trazalog** [comment]
Solucionado en v 1.5.38
