### ISSUE TITLE
Producción-->ABM No consumibles: error al crear un código post eliminado

### ISSUE THREAD

**Issue by aalfaro-trazalog** [Trazalog/traz-prod-trazasoft#176]
v 1.5.36

Descripción:
Si se elimina un no consumible y luego se intenta crear otro con mismo nombre de código del eliminado, el sistema muestra un alert "El código del no consumible ingresado, ya se encuentra creado". Esto sucede porque el sistema crea un borrado lógico.

![image](https://user-images.githubusercontent.com/87376576/153870651-73f80909-9f05-4708-9301-ef9de7d778f6.png)

Pasos para reproducir:
1. En menú, seleccionar Producción
2. Click en ABM No consumible
3. Click en boton "Agregar"
4. Completar los campos requeridos
5. Click en "Guardar"

**Comment by floto-trazalog** [comment]
La validación es correcta por lo que no se puede crear un no consumible con el mismo código, debido a problemas con la trazabilidad. La validación es correcta.

v2.1.7.8
