### ISSUE TITLE
Producción-->Producción de Lotes | Operario: el NC inhabilitado se activa al ser asignado a un lote

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-prod-trazasoft#182]
Ambiente Test - v1.5.36

**Descripción:**
Cuando el supervisor realiza un Reporte de Producción y le asigna un NC, el sistema no comprueba si el NC está o no habilitado, y en el caso que está inhabilitado lo activa sin consultar. Lo correcto sería que se abra una modal notificando que ese NC está inhabilitado

https://user-images.githubusercontent.com/88331456/154146800-d4b0a05e-7512-4201-b852-24e9ffa2a9ae.mp4

**Pasos para reproducir:**

1. En el menú Producción 
2. Dar click en producción de Lotes | Operario
3. Seleccionar una tarea del listado y dar click sobre ella
4. Completar los campos
5. Dar click en el botón "Agregar"
6. Dar click en el botón de acción "+"
7. Ingresar el código de un NC inhabilitado
8. Presionar la tecla _Enter_ o dar click en la lupa

_Aquí se visualiza la habilitación del No_
![QUIN](https://user-images.githubusercontent.com/88331456/154147217-272f0ee8-1f0e-4a0a-b197-1fd6c793b554.png)_
 Consumible

**Comment by aalfaro-trazalog** [comment]
Solucionado en v 1.5.38
