### ISSUE TITLE
Producción-->Rec No Consumibles: al consultar los NC no muestra los lotes que trae

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-prod-trazasoft#184]
Ambiente Test - v1.5.36

**Descripción:**
Al llamar los NC para vaciarlos y el sistema no muestra el lotes que trae en la tabla, por ende se recomienda agregar la columna del lote que trae el No Consumible

![BUG-1616](https://user-images.githubusercontent.com/88331456/154341218-d4ef55c0-0b83-4443-9e0b-353b82d15893.png)

**Pasos para reproducir:**
1.   En el menú Producción 
2. Dar click en Rec No Consumibles
3. Completar los campos requeridos y teclear "enter"

**Comment by aalfaro-trazalog** [comment]
Solucionado en v 1.5.38
