### ISSUE TITLE
Logística --> Salida de camión: agregar validación de tara<bruto

### ISSUE THREAD

**Issue by aalfaro-trazalog** [Trazalog/traz-prod-trazasoft#187]
v 1.5.37

Descripción:
El sistema no válida que la tara debe ser menor al peso bruto. 
Además, cuando ocurre el caso de que el bruto es mayor, muestra el neto en cero.

![tara bruto](https://user-images.githubusercontent.com/87376576/155187461-b8ba839b-8ee2-48d1-a40b-46a25b8e16fa.png)

**Comment by smustafa-trazalog** [comment]
Sin resolver
![image](https://user-images.githubusercontent.com/98842352/158253578-672e9c88-43d0-4db6-b69a-d0433b858029.png)

Bugh, casillas de establecimiento de origen y de salida aparecen tildados como cargados correctamente, pero no poseen datos

**Comment by floto-trazalog** [comment]
Solucionado antes de v2.1.4.5
