### ISSUE TITLE
Logística --> Recepción MP: validar el tipo de número entero

### ISSUE THREAD

**Issue by aalfaro-trazalog** [Trazalog/traz-prod-trazasoft#188]
v 1.5.37

Descripción:
Luego de completar todos los campos requeridos, al agregar, aparece un cartel de error "completar todos los campos requeridos". 

Además el número del bruto y tara se coloca como flotante, cuando se cargaron como enteros. 

https://user-images.githubusercontent.com/87376576/155189783-2b3e7f06-b9a3-4eaf-9044-0f525facff30.mp4

PASOS PARA REPRODUCIÓN
1. LOGISTICA
2. ENTRADA | RECEPCIÓN
3. NUEVA ENTRADA RECEPCIÓN 
4. RECEPCIÓN MP
5. CARGAR DATOS

**Comment by floto-trazalog** [comment]
Duplicado, se deja el #379
