### ISSUE TITLE
Produccion->Produccion de lotes: El boton flotante estorba

### ISSUE THREAD

**Issue by Nahuel1705** [Trazalog/traz-prod-trazasoft#19]
ID del bug: NA-01

Funcionalidad: Botón "Nueva etapa"

Descripción: Al ser un botón flotante este queda fijo en la pantalla mientras la pagina se desplaza, esto provoca que a veces estrobe según el contenido que se muestra. También molesta a la hora de scrollear la tabla particularmente en la versión de tablet.

El botón se superpone con el dropdown de la cuenta de usuario:
![image](https://user-images.githubusercontent.com/56811317/118293861-7ed40500-b4b0-11eb-91e1-e6895cb1cce8.png)

El botón estorba con el scrolling en la versión para tablets:
![chrome-capture (1)](https://user-images.githubusercontent.com/56811317/118293924-8f847b00-b4b0-11eb-840c-9a5e03afe177.gif)

El botón se superpone a la tabla en la versión de escritorio:
![chrome-capture](https://user-images.githubusercontent.com/56811317/118294347-01f55b00-b4b1-11eb-9ee7-d4bfef69d166.gif)

**Comment by aalfaro-trazalog** [comment]
Solucionado en v 1.5.35
