### ISSUE TITLE
PRODUCCIÓN -->ETAPAS PRODUCTIVAS, AGREGAR ETAPA: Creo etapa productiva, me indica cartel que se creo correctamente, pero no aparece en la lista de tareas

### ISSUE THREAD

**Issue by smustafa-trazalog** [Trazalog/traz-prod-trazasoft#191]
Versión v1.5.37
Ambiente Test

Descripción:
Cuando creo etapa productiva, me indica cartel que la etapa se creo correctamente, pero al buscarla no aparece en la lista de tareas creadas. En vídeo de muestra sucedió el problema, luego intente cargar nuevamente un articulo y lo cargo correctamente pudiéndolo encontrar en la lista.

Video 1 - no me aparece en lista tarea agregada

https://user-images.githubusercontent.com/98842352/155209133-2632e5ef-e2f3-4d98-82be-e2f59a021a4d.mp4

 Vídeo 2 - me aparece en lista las tareas agregadas

https://user-images.githubusercontent.com/98842352/155209685-260af3aa-0961-493a-9be4-ab695da011e3.mp4

Pasos para reproducción.

1. Producción
2. Etapas productivas
3. Agregar
4. Guardar
5. Buscar etapa creada

**Comment by smustafa-trazalog** [comment]
SIGUE SIN BUSCAR ARTICULOS CARGADOS.

**Comment by floto-trazalog** [comment]
solucionado antes de v2.0.18
