### ISSUE TITLE
PRODUCCIÓN --> AMB NO CONSUMIBLES: Cuando activo un no consumible dado de alta se actualiza toda la pagina y debo buscar nuevamente el articulo

### ISSUE THREAD

**Issue by smustafa-trazalog** [Trazalog/traz-prod-trazasoft#193]
Versión v1.5.37
Ambiente Test

Descripción:
Cuando activo un no consumible dado de alta se actualiza toda la pagina y debo buscar nuevamente el articulo que activé. Seria bueno que al correr el switch para activar el articulo la lista quede con el filtro o busqueda que se realizo

https://user-images.githubusercontent.com/98842352/155215218-d3ee5c71-646b-4a09-b530-e482d4f91662.mp4

Pasos a reproducir
1. Producción
2. ABM no consumibles
3. acciones, deslizar switch de activación

**Comment by smustafa-trazalog** [comment]
SIN RESOLVER V2.0.7.1

**Comment by floto-trazalog** [comment]
Solucionado en v2.1.16 (aproximadamente)
