### ISSUE TITLE
Logística-->Carga de camiones: en "Camiones ingresados" se visualizan artículos con stock en cero

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-prod-trazasoft#195]
Ambiente test - v2.0.2

**Descripción:**
Al realizar una carga de camión y buscar en el campo "Camiones ingresados" un artículo X se pueden visualizar incluso los que tienen stock en cero y eso no correspondería a dicha gestión

![BUG-08](https://user-images.githubusercontent.com/88331456/157065577-67f67417-65ac-4855-8c73-849c84e03886.png)

**Pasos a reproducir:**

1. En el menú Logística
2. Dar click en "Carga Camión"
3. Completar los campos obligatorios
4. Completar "Códigos Lotes"

**Comment by smustafa-trazalog** [comment]
SIN RESOLVER v2.0.7.1

**Comment by floto-trazalog** [comment]
Duplicado, se deja el issue actualizado #382
