### ISSUE TITLE
Producción --> ABM No Consumibles-->Agregar nuevo, completar datos

### ISSUE THREAD

**Issue by smustafa-trazalog** [Trazalog/traz-prod-trazasoft#198]
Ambiente test v2.0.2

Descripción:
Cuando selecciono agregar nuevo "No consumible" aparecen todas las casillas vacias, pero verificadas en verde como si estuviese ok la carga

![image](https://user-images.githubusercontent.com/98842352/157094773-8cfcc048-d3c5-470f-bf1e-ad4909321ea4.png)

https://user-images.githubusercontent.com/98842352/157096165-27da7988-5b60-449d-a021-d45811b51b9b.mp4

Pasos para la reproducción:

En menú Producción dar click en ABM No Consumibles
Click en el botón "Agregar"

**Comment by floto-trazalog** [comment]
Solucionado antes de v2.1.16.1
