### ISSUE TITLE
Producción-->Producción de Lotes: al iniciar etapa de pelado no se puede cerrar la ventana de carga de datos

### ISSUE THREAD

**Issue by smustafa-trazalog** [Trazalog/traz-prod-trazasoft#205]
Ambiente Test v2.0.3

Descripción:
Al ingresar a la etapa de "Pelado", sin cargar datos, y hacer click en boton cerrar no lo realiza.

https://user-images.githubusercontent.com/98842352/157742692-939a097d-53ed-4e95-a4a1-27f4e1544ce3.mp4

1. En Producción dar click en Producción de Lotes
2. Click en el botón + (crear nueva etapa)
3. Seleccionar "Pelado"
4. No completar ningun dato
5. Click en el botón "Cerrar"

**Comment by floto-trazalog** [comment]
Solucionado v2.1.10
