### ISSUE TITLE
Producción de Lotes--> Nueva etapa: boton de cerrar no cierra la ventana

### ISSUE THREAD

**Issue by smustafa-trazalog** [Trazalog/traz-prod-trazasoft#206]
Ambiente test v2.0.3

Descripción: al tratar de cerrar la ventana, el boton "cerrar" no realiza la acción.

https://user-images.githubusercontent.com/98842352/157952764-c0c617ea-e022-4406-9e03-4a69218c4497.mp4

Pasos para reproducir:

1. En menú seleccionar Producción
2. Click en producción de lotes
3. Click en Nueva etapa
4. Etapa de fraccionamiento creada

**Comment by aalfaro-trazalog** [comment]
Solucionado v 2.1
