### ISSUE TITLE
Producción-->Producción de lotes-->Gestión: cambiar formulario de pedido de materiales

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-prod-trazasoft#257]
**Descripción:**
Al gestionar una etapa de fraccionamiento el sistema debería traer el formulario completo por defecto con los datos cargados del usuario que esté tomando esa tarea.

![image](https://user-images.githubusercontent.com/88331456/169388111-3453c491-09d6-4a4e-b535-8b9dc9a32ed0.png)

**Pasos a seguir:**

1. En producción
2. Clic en Producción de lotes
3. Clic en gestionar etapa fraccionamiento
4. Clic en Tomar tarea
5. Clic en Realizar tarea

**Comment by aalfaro-trazalog** [comment]
@lbgarcia este ticket lo vamos a desestimar, y en su lugar hemos determinado que el formulario se va a ocultar. En próximas versiones se hara una mejora para que el formulario sea dinámico y tenga campos customizados segun la empresa lo requiera.
