### ISSUE TITLE
Producción-->Producción de lotes: al gestionar etapa de Fraccionamiento trae el formulario de Ped. Materiales

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-prod-trazasoft#267]
Ambiente test - v2.0.13.6

**Descripción**
Al gestionar una etapa del tipo fraccionamiento se recomienda quitar el formulario de Pedido Materiales puesto que es de la etapa del tipo simple.

![image](https://user-images.githubusercontent.com/88331456/170784083-74018e99-540d-4288-b977-2b0d24a9339f.png)

**Pasos a seguir**

1. Clic en Producción
2. Clic en Producción de lotes
3. Posicionarse sobre una etapa de fraccionamiento
4. Clic en el botón "Gestionar"

**Comment by aalfaro-trazalog** [comment]
Esto no es un bug, es correcto que se muestre en la pantalla de pedidos de materiales.
