### ISSUE TITLE
Producción-->Producción de lotes-->Gestionar: al reportar un fraccionamiento no trae lotes para fraccionar

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-prod-trazasoft#290]
Ambiente test - v2.0.15.1

**Descripción**
Al gestionar un reporte de Fraccionamiento el sistema no trae los lotes para fraccionar y, lo correcto es que figure la sección de Pedidos de Materiales al iniciar la etapa para que se pueda realizar el pedido de materia prima

![image](https://user-images.githubusercontent.com/88331456/174126993-f50b7c8e-9937-4979-96c0-e16d006e1ef5.png)

**Pasos a seguir**
1. En Producción
2. Clic en Producción de lotes
3. Clic en el botón de acción Gestionar
4. Clic en el botón Reporte de Fraccionamiento

**Comment by aalfaro-trazalog** [comment]
Solucionado en v 2.1
