### ISSUE TITLE
Producción--Producción de lotes-->Gestionar: no muestra la sección de Pedido de materia prima

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-prod-trazasoft#291]
Ambiente test - v2.0.15.1

**Descripción**
Al gestionar una etapa de fraccionamiento no se muestra la sección para hacer el Pedido de materia prima, entonces esto se relaciona con el issue #290 

https://user-images.githubusercontent.com/88331456/180502072-70300797-f2fc-4016-8c9c-758bb85924c4.mp4

**Pasos a seguir**
 1. En prodcucción
 2. Clic en Producción de lotes
 3. Clic en el botón de acción "Gestionar"

**Comment by aalfaro-trazalog** [comment]
Solucionado en v 2.1
