### ISSUE TITLE
Producción--> Fraccionamiento: mejoras general para la vista

### ISSUE THREAD

**Issue by aalfaro-trazalog** [Trazalog/traz-prod-trazasoft#314]
Descripción: 

Agregar mejoras:
-En acciones, agregar el botón editar, ver detalle y cambiar icono al eliminar
-El ver detalle abre un modal que muestra los detalles del pedido, **y si el mismo tenía asociado una receta, debe mostrar el detalle de cada artículo asociado a la misma.**
-El botón de iniciar y cerrar, cambiarlo de lugar.

![Fracc1](https://user-images.githubusercontent.com/87376576/182471754-ac91386b-ea64-4882-9e64-82eb7d138ab1.png)

![Fracc2](https://user-images.githubusercontent.com/87376576/182471777-7d2a8fc9-116b-4197-85e2-780b187546fa.png)

**Comment by floto-trazalog** [comment]
Solucionado en v2.1
