### ISSUE TITLE
Producción--> poder editar o eliminar lote productivo de una etapa simple

### ISSUE THREAD

**Issue by aalfaro-trazalog** [Trazalog/traz-prod-trazasoft#315]
Descripción:

En la pantalla
Producción--> Producción de lotes--> Etapa--> Simple

Se debe poder editar o anular el lote mientras se cumpla una de estas condiciones:

-Si la etapa está planificada.
-Si la etapa está iniciada pero no se han tomado materias primas.

En la pantalla se mostrará un botón de editar en las cabeceras (Sólo cuando se cumpla lo anterior):

![editar lotes](https://user-images.githubusercontent.com/87376576/182642554-ac8f74fc-40bd-4004-a904-1e96309273e7.png)

**Comment by floto-trazalog** [comment]
### Falta agregar una mejora:

![image](https://user-images.githubusercontent.com/88331456/196500790-7555510d-2cd8-450b-a68d-a0cf76c5628a.png)

Que al gestionar la etapa el sistema muesrte la pantalla con los campos de solo lectura y se activen una vez que el se presiona el botón editar, señalado en la imagen

**Comment by floto-trazalog** [comment]
Solucionado
