### ISSUE TITLE
SOPORTE--> Prod de lote Op: no funciona filtrar por producto y agregar descripción de etapa

### ISSUE THREAD

**Issue by aalfaro-trazalog** [Trazalog/traz-prod-trazasoft#325]
Ambiente cliente ISOLA

Descripción:
Al seleccionar un producto, el sistema trae todos los productos, sin filtrar por tipo.
![image](https://user-images.githubusercontent.com/87376576/187223719-92568173-11f3-4359-9b39-0c1ffa149af0.png)

Agregar el detalle de a que etapa hace referencia
![image](https://user-images.githubusercontent.com/87376576/187540394-05301f29-cad3-49c8-a65e-9a727c43c7bd.png)

**Comment by floto-trazalog** [comment]
Solucionado en v2.1.4.6
