### ISSUE TITLE
SOPORTE--> Logistica--> Recepción de MP: que filtre solo por MP

### ISSUE THREAD

**Issue by aalfaro-trazalog** [Trazalog/traz-prod-trazasoft#326]
Ambiente cliente ISOLA

Descripción:
Al seleccionar el producto de ingreso que filtre solo los frescos o Materias primas, hoy muestra todo el maestro de articulos.

Sugerencia Rodo:

- Estos productos codificarlos como "_Commodity_" para ello agregar en tabla interna del sistema.
- Agregar un método que te permita filtrar por lista 2.
- Llamar al servicio que llama a tier_id

![image](https://user-images.githubusercontent.com/87376576/187228191-23366f00-537e-468b-9fba-018042021e9d.png)

**Comment by floto-trazalog** [comment]
Solucionado v2.1.4.6
