### ISSUE TITLE
SOPORTE--> Producción--> Producción de Lote: No aparecen todos los usuarios

### ISSUE THREAD

**Issue by aalfaro-trazalog** [Trazalog/traz-prod-trazasoft#329]
Ambiente PROD - Termotanques Millenium (TEMI)

Descripción:
Si bien aparecen todos los usuarios de la lista del Dnato, @ffernandez-trazalog durante las pruebas al querer asignar un usuario detectó que en el select faltaba uno. Consultarle a Fede cuál es el faltante para verificar si existe en la BD, si necesita configurarse o si es necesario crearlo.

![image](https://user-images.githubusercontent.com/87376576/187292004-5e9a1e50-2d98-4c1c-bc85-97ec48a0a736.png)

**Comment by floto-trazalog** [comment]
Solucionado en v2.1.4.6
