### ISSUE TITLE
Producción -->Producción de Lotes -->En pestaña "Todas" el sistema completa las casillas vacías con el dato: null

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-prod-trazasoft#33]
v1.5.8.8

Descripción: Al clickear en la pestaña "Todas" automáticamente en la columna de "Producto" y "Cantidad" los datos vacíos los autocompleta con "Null".

Sugerencia: Contemplar el requerimiento con el cliente a su conveniencia. 

Pasos a reproducir:
   1- En el módulo "Producción" - "Etapas" click en pestaña "Todas"
   
![CAPI13](https://user-images.githubusercontent.com/88331456/129420141-1f02c0b2-5e5f-48a1-b990-d845735ce00b.png)

![CAPIT13](https://user-images.githubusercontent.com/88331456/129420149-e3a7da2c-df12-4732-bf2c-a2f35d4ee11a.png)

![CAPITU13](https://user-images.githubusercontent.com/88331456/129420150-b0944648-ff67-4388-9113-5adec533d380.png)

**Comment by focafunk** [comment]
En realidad me parece que lo hace en todas, el tema es el estado... creo que con En curso tira null, ya investigo

![image](https://user-images.githubusercontent.com/38109047/141373380-1ae19168-e6d0-42fe-b967-e04603be6c91.png)
