### ISSUE TITLE
SOPORTE--> Almacenes--> Salida de depósito: error al seleccionar depósito

### ISSUE THREAD

**Issue by aalfaro-trazalog** [Trazalog/traz-prod-trazasoft#330]
Ambiente PROD - Termotanques Millenium

Descripción:
En Almacenes--> Salida de depósito, en la sección de Productos a cargar, cuando se selecciona el _depósito de origen_ aparece el cartel de error. Esto se debe a que cuando se selecciona un depósito, los artículos guardados en dicho lugar no están cargados con unidad de medida.

![image](https://user-images.githubusercontent.com/87376576/187294552-728482a0-1563-4bdc-a37f-b787f5805392.png)

**Comment by floto-trazalog** [comment]
Solucionado en v2.1.4.6
