### ISSUE TITLE
SOPORTE--> Producción--> Prod de Lote | Operarios: poder generar QR de reporte de producción

### ISSUE THREAD

**Issue by aalfaro-trazalog** [Trazalog/traz-prod-trazasoft#331]
Ambiente Termotanque Millenium

Descripción:
En reporte de prod operario, agregar el generar QR y poder imprimirlo, debe ser igual que el que aparece en Producción--> Producción de lotes--> Etapa simple--> Gestionar--> Reporte de Producción

Además, se agrega como mejora, agregar una columna de acciones con los iconos de ver detalle, QR, agregar no consumible y eliminar.

![Maqueta Propuesta QR de producto final (1)](https://user-images.githubusercontent.com/87376576/188709598-094ee2f4-0197-4017-a840-88be1358a51e.png)

**Comment by floto-trazalog** [comment]
Solucionado en v2.1.16
