### ISSUE TITLE
Producción-->Producción de lotes-->Fraccionamiento: no agrega reporte de fraccionamiento

### ISSUE THREAD

**Issue by aalfaro-trazalog** [Trazalog/traz-prod-trazasoft#337]
v 2.1.4.5

Descripción:
En el reporte de fraccionamiento, luego de agregar todos los campos, si se presiona el botón agregar no funciona.

![image](https://user-images.githubusercontent.com/87376576/188644146-ea9c6ba8-85cf-4baa-b351-3f03e40b5bdc.png)

Pasos a reproducir

1. En Módulo Producción, clic en el submódulo "Producción de lotes"
2. Clic en el botón "Consolidación"
3. Clic en el botón "Crear Nueva etapa"
4. Completar los campos obligatorios
5. Clic en el botón "Agregar"

**Comment by floto-trazalog** [comment]
Solucionado v2.1.10
