### ISSUE TITLE
Producción de Lotes--> Reporte de Prod: poder asociar un no consumible

### ISSUE THREAD

**Issue by aalfaro-trazalog** [Trazalog/traz-prod-trazasoft#338]
v2.1.4.5 

Descripción:
En el reporte de producción, agregar el campo de No consumible

![image](https://user-images.githubusercontent.com/87376576/188659543-b8af7987-1258-44de-a3d0-9ce481d31b02.png)

**Comment by floto-trazalog** [comment]
Solucionado en v2.1.17

Se han realizado cambios respecto al maquetado para esta funcionalidad. Como se muestra en la imagen

![image](https://user-images.githubusercontent.com/88331456/221916024-a00792e1-0fff-4aa7-b59b-0ef91a9fb57d.png)
