### ISSUE TITLE
Producción -->Producción de Lotes: No figura la Etapa "Finca" en la pestaña superior

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-prod-trazasoft#34]
v1.5.8.8

Descripción: Al clickear en "Producción de Lotes" la Etapa "Finca" dejó de figurar en las pestaña superior sin embargo está registrada.

Pasos a la reproducción:
1- En módulo Producción, click en Producción de Lotes
![Png3](https://user-images.githubusercontent.com/88331456/129794440-54b9e66b-09b0-4cd0-8bd0-01f150606e65.png)

**Comment by focafunk** [comment]
Lo que muestra abajo son los lotes en curso, que fueron creados tomando como plantilla una etapa, si luego vamos y borramos la etapa, igual seguirán apareciéndo aunque dicha etapa este borrada, voy a probar borrando la actual etapa FINCA en mayusculas y tomando screenshot

![image](https://user-images.githubusercontent.com/38109047/141378285-a1ed3638-3446-412e-baad-ebb0b655ad68.png)

como verás se sigue viendo en la lista de Lotes, a pesar de que la borre en la base de datos

![image](https://user-images.githubusercontent.com/38109047/141378347-924a0021-4bdc-45b8-98e6-2d8d59e552c2.png)

ahora vuelvo a habilitarla, y nuevamente aparece en la lista... las etapas funcionan como "Templates" de los lotes productivos o batches

![image](https://user-images.githubusercontent.com/38109047/141378647-ba300c1c-24ff-40d0-bb36-71da539b2f1d.png)
