### ISSUE TITLE
Logística--> Recepción MP: no permite agregar datos ingreso-salida

### ISSUE THREAD

**Issue by aalfaro-trazalog** [Trazalog/traz-prod-trazasoft#345]
Reproducido en: 

- Ambiente PRD - Millenium - v2.1.3

- _Ambiente Demo - Empresa Metalmecánica - Usuario: Jperez_ - v 2.0.16

Descripción:
Cuando se realiza la carga de datos de ingreso y salida, la unidad de medida aparece de sólo lectura y requerido, cuando se desea agregar aparece el alert "complete los campos obligatorios" siendo que ya se completaron todos excepto la un de medida.

![image](https://user-images.githubusercontent.com/87376576/186207775-e1127636-c57c-428c-9692-c914a9922cd6.png)

**Comment by floto-trazalog** [comment]
Solucionado en test - v2.1.8.3.2
