### ISSUE TITLE
Reportes --> Maqueta de Reportes de Producción

### ISSUE THREAD

**Issue by aalfaro-trazalog** [Trazalog/traz-prod-trazasoft#346]
Descripción:
Se adjunta una maqueta con las mejoras y cambios para _Reportes de Producción_. 

Nota: este estilo de pantalla de reporte, contiene elementos que deben mantenerse standars para el resto de pantallas que utilicen la opción de filtro. Dichos elementos comunes son:
-Fecha desde y Fecha hasta con botón de varita
-Exportar a Excel, Exportar a PDF, Copiar e Imprimir
-Los últimos datos registrados y almacenados en la tabla se muestran por defecto en el tope.

https://drive.google.com/drive/u/0/folders/17UpEq_AQvUkBh-OFHt7kOcRqBCJoBAfG

Pasos para reproducir:

1. En Menú seleccionar "Reportes"
2. Click en "Producción"

**Comment by floto-trazalog** [comment]
Solucionado
