### ISSUE TITLE
Producción -->Producción de Lotes: Al editar una Etapa, en el campo Fecha le suma la hora 

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-prod-trazasoft#36]
Descripción: en el campo "Fecha" se considera fecha y hora cuando debe ubicarse solo la fecha.

Sugerencia: Verificar el formato de la fecha dd/mm/aaaa.

Pasos:
1- Ingresar en módulo "Producción", click en Producción de Lotes
2- Elegir en la tabla uno de los registros
3- Hacer click en el botón Editar, en la columna acciones

![Fito](https://user-images.githubusercontent.com/88331456/129918417-9a3da8d6-25fe-443e-aae5-2c635e9e6486.png)

**Comment by aalfaro-trazalog** [comment]
@lbgarcia en PROD funciona bien, pero en TEST nuestro no.
