### ISSUE TITLE
Producción-->Producción de lotes-->Iniciar etapa/Planificar: que recupere la sección de Planificación de tareas vacía

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-prod-trazasoft#425]
Ambiente TEST - v2.1.17

**Descripción**
Al iniciar una etapa o planificarla en el sector de **Planificación de Tareas**, el sistema recupera todas las tareas que se encuentran asignadas y lo correspondiente sería que no traiga ninguna puesto que recién se comienza con dicha etapa

**Nota**
Se adjunta el video para más detalles

_video-1_

https://user-images.githubusercontent.com/88331456/222795844-c0c8a53a-94ef-4632-a860-bfdfac08beb0.mp4

_video-2_

https://user-images.githubusercontent.com/88331456/222795829-beee3288-4223-466b-8db5-d42fc113ea12.mp4

**Comment by floto-trazalog** [comment]
Solucionado en v2.2.6.1

**Comment by gnicolia-trazalog** [comment]
Se reabre en V 2.2.17

**Comment by floto-trazalog** [comment]
Solucionado en v2.2.20
