### ISSUE TITLE
Producción-->Producción de lotes-->botón +: al agregar nuevo lote muestra cartel de error & duplica

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-prod-trazasoft#431]
Ambiente TEST - v2.2.15

**Descripción:**
al agregar nuevo Lote, muestra un cartel de error y luego, duplica el lote, uno con estado: "Planificado" (al presionar el botón -Guardar) y el otro, con estado: "Curso" (al presionar el botón -Iniciar Etapa)

![image](https://github.com/Trazalog/traz-prod-trazasoft/assets/88331456/a12e0c12-7c74-4e5e-bf4e-97370cee608d)

https://github.com/Trazalog/traz-prod-trazasoft/assets/88331456/0a3b8764-a1c7-4c27-abe9-eafb6d71137d

**Comment by jfernandez-trazalog** [comment]
Gera Ramos.

**Comment by floto-trazalog** [comment]
Solucionado en v2.2.20, (se estima que en la versión anterior).
