### ISSUE TITLE
Produccion--> Logistica--> Carga camion: Falla al recuperar lotes del establecimiento

### ISSUE THREAD

**Issue by gnicolia-trazalog** [Trazalog/traz-prod-trazasoft#433]
Ambiente de Test v 2.2.15

Descripcion: Al completar el  campo de establecimiento el sistema muestra un cartel de error como se muestra a continuacion 

![image](https://github.com/Trazalog/traz-prod-trazasoft/assets/146888657/94427a5c-20a6-4994-b0f4-baeba61ecbcb)

Esto bloquea al usuario guardar el registro de la carga del camion.

Pasos a seguir :

1. Produccion 
2. Logistica
3. Carga de camion
4. Completar el campo "establecimiento"

**NOTA:**
se agrega un video con audio y el error

https://github.com/Trazalog/traz-prod-trazasoft/assets/88331456/8211b208-1874-4ae8-acdb-d58451bda7b4

_Error de red_

{"status":false,"header":"HTTP\/1.1 500 Internal Server Error\r\nContent-Type: application\/xml; charset=UTF-8\r\nDate: Mon, 06 Nov 2023 13:56:38 GMT\r\nTransfer-Encoding: chunked\r\n\r\n","data":"
<option value='0' data-foo='' selected disabled>
    -  Seleccionar  - <\/option>","code":500}

![image](https://github.com/Trazalog/traz-prod-trazasoft/assets/88331456/6a4a4358-0de2-47a4-852e-721c3940306f)

y también

![image](https://github.com/Trazalog/traz-prod-trazasoft/assets/88331456/daff02da-3149-4819-b008-637675cafac9)

**Comment by gnicolia-trazalog** [comment]
Continua igual en V 2.2.18.1

**Comment by floto-trazalog** [comment]
Se baja prioridad, porque actualm no se está usando el módulo

**Comment by jfernandez-trazalog** [comment]
Gera Ramos.-

**Comment by floto-trazalog** [comment]
Solucionado
