### ISSUE TITLE
SOPORTE-->Logística-->Listado de camiones: que solo se visualicen los camiones distinto al estado "Finalizado"

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-prod-trazasoft#441]
Ambiente Test - v2.3.2

**Descripción:**
Que solo se vean en la tabla de registros todos los camiones con el estado =! "Finalizados"

![image](https://github.com/Trazalog/traz-prod-trazasoft/assets/88331456/1b6712a3-6cf4-4404-8216-84ab68798331)

**Comment by jfernandez-trazalog** [comment]
Gerardo Ramos.

**Comment by floto-trazalog** [comment]
Solucionado en v2.4.3
