### ISSUE TITLE
SOPORTE-->Logística-->Entrada | Recepción MP: que permita ingresar el "Código Lote" 

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-prod-trazasoft#443]
Ambiente Test - v2.3.9.2

**Descripción:**
En la Recepción MP, en el formulario de título: **Ingreso**; al completar los campos requeridos el sistema no permite ingresar el código del lote
Se ha trabajado el siguiente issue https://github.com/Trazalog/traz-prod-trazasoft/issues/416

**Nota:** se deja el video, activar el audio.

https://github.com/user-attachments/assets/09ed23ef-7197-413a-9253-1e9f5c8ad0b5

**Pasos a reproducir:**
1. Ingresar en el menú Logística
2. Clic en Entrada | Recepción MP
3. Clic en el botón: _Recepción MP_
4. Completar los campos obligatorios: Comprobante, Establecimiento, Proveedor, Transportista, Patente, Acoplado, Conductor, Tipo, Bruto, Tara, Neto, **Código Lote**, Producto, Descripción, Unidad Medida, **Cantidad** 

**Resultado esperado:**
Que permita ingresar el código del lote del camión como se indica en el video y permita ingresar la **Cantidad**

**Comment by jfernandez-trazalog** [comment]
Pablo Marrelli.

**Comment by floto-trazalog** [comment]
Solucionado en v2.3.10
