### ISSUE TITLE
Logística-->Entrada | Recepción MP-->Recepción MP: al buscar con la lupa no guarda el dato "Patente"

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-prod-trazasoft#444]
Ambiente Test - v2.3.10

**Descripción:**
**Pre-condiciones:** tener cargado un camión con al menos un lote y cantidad de stock
En el formulario de Recepción MP, al ingresar el dato **Patente** y buscar con la lupa los lotes cargados en dicho camión, el sistema recupera los datos correctamente, pero refresca este campo obligando al usuario a completarlo de forma manual

**Resultado esperado:** que al presionar la lupa de la búsqueda del camión, el sistema recupere los datos y autocomplete como lo está realizando ahora y que mantenga el dato de la patente ingresado

_Se deja el video para mayor detalle_

https://github.com/user-attachments/assets/469a0a4e-cfdb-45a1-be0d-84f115818157

**Pasos a reproducir:**
1. En el módulo Logística
2. Clic en el submenú Entrada | Recepción MP
3. Clic en el botón **Recepción MP**
4. Completar los campos obligatorios. Luego, al llegar al campo **Patente** y completarlo
6. Presionar el botón "Buscar" (lupa)

**Comment by jfernandez-trazalog** [comment]
Gera Ramos.

**Comment by floto-trazalog** [comment]
Soluc.
