### ISSUE TITLE
ARMO-->Logística-->Carga Camión: modificaciones varias al imprimir un remito

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-prod-trazasoft#445]
Ambiente Test - v2.4.0

**Descripción:**
Al momento de la impresión es vital corregir los siguientes ítems: 

1. Los importes son con 2 decimales
2. Respetar la alineación de la maqueta, por ejemplo, la columna "Cantidad" está muy ancha y hay poco espacio para la descripción
Entonces, se recomienda en la columna **Cantidad** dejar el ancho de la palabra y ese espacio sobrante dejarlo para la columna **Descripción**
3. El campo total va alineado a la derecha, agregar el siímbolo pesos y el importe que tenga 2 decimales.

**Pasos a reproducir:**
1. En el menú Logística
2. Clic en Carga camión
3. Completar los campos obligatorios
4. Clic en el botón "Carga camión"
5. Clic en el botón "Finalizar"

![image](https://github.com/user-attachments/assets/28ca17c1-b3cc-4a3f-b452-aa3eded7af78)

Se dejan credenciales de las pruebas realizadas -->
--> URL: http://10.142.0.16/test/traz-comp-dnato/main/login
user: [jperez@prueba.com](mailto:jperez@prueba.com)
pass: 12345

**Comment by jfernandez-trazalog** [comment]
Gera Ramos.-

**Comment by floto-trazalog** [comment]
Solucionado en v2.4.3
