### ISSUE TITLE
ARMO-->Logística-->Carga camión: agregar el campo Stock

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-prod-trazasoft#447]
Ambiente Test - v2.4.1

**Descripción:**
Al completar los campos de la carga del camión, el sistema debe recuperar el campo de solo lectura del stock como lo indica la maqueta
se adjunta imagen de la maqueta:
![image](https://github.com/user-attachments/assets/7a6d8538-fc4a-4e62-8d19-4f172f4ee884)

Actualmente, figura el stock debajo del Cod del Lote, pero es pequeño y esto puede confundir al usuario.
se adjunta img.

![image](https://github.com/user-attachments/assets/aee4f558-0a7c-4d6c-80af-60a4e1b17206)
 
**Pasos a reproducir:**
1. En el menú Logística
2. Clic en Carga camión
3. Completar los campos obligatorios

**Comment by jfernandez-trazalog** [comment]
Pablo Marrelli.-
