### ISSUE TITLE
Logística-->Rep Hist Remitos: que recupere el logo actual

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-prod-trazasoft#448]
Ambiente Test - v2.4.3

**Descripción:**
En la re-impresión del remito figura el logo viejo y lo adecuado sería que recupere el logo actualizado 

https://github.com/user-attachments/assets/92fd284e-68c9-4609-bbcb-7cedd9190e53

**Pasos a reproducir:**

1. En el menú Logística
2. Clic en Rep Hist Remitos
3. Elegir un registro
4. Clic en el botón de acción "Imprimir"
5. Clic en el botón "Imprimir"

**Comment by jfernandez-trazalog** [comment]
Pablo Marrelli.-
