### ISSUE TITLE
Producción-->Producción de lotes: al realizar un reporte, que el formulario de calidad NO sea obligatorio 

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-prod-trazasoft#450]
Ambiente Test - v2.4.4

**Descripción:**
Al realizar un reporte de producción el sistema muestra un aviso en pantalla indicando que se debe asignar una tarea para avanzar con el reporte. Y lo adecuado sería que valide SI existe una tarea de "control de calidad" ENTONCES, que **no** premita realizar el reporte hasta que se apruebe dicha tarea. SINO, (que NO exista una tarea de "control de calidad") ENTONCES, que permita realizar el reporte de producción, normalmente.

https://github.com/user-attachments/assets/4f5a40d9-47af-4ec4-95c5-bcff30cfe3b3

**Resultado esperado:**
Que al completar los campos requeridos y dar clic en el botón "Reporte de producción" el sistema permita continuar el proceso productivo.

**Pasos a reproducir:**

1. En Producción
2. Porducción de lotes
3. Gestionar etapa simple
4. Deslizar la pantalla hasta el final y dar clic en el botón "Reporte de producción"

**Comment by jfernandez-trazalog** [comment]
Gera Ramos.-

**Comment by floto-trazalog** [comment]
Solucionado en test v2.4.5.1
