### ISSUE TITLE
Producción --> ABM No Consumibles-->Agregar nuevo: colocar la Fecha de Inicio y Vencimiento, & agregar Fecha de Alta

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-prod-trazasoft#59]
Ambiente Test - v1.5.35

**Descripción:**
Al "Agregar" un nuevo No consumible se recomienda colocar La Fecha de Inicio y Fecha de Vencimiento. Y lo correcto sería que valide una fecha a partir de la actual porque permite ingresar cualquier fecha

**Pasos para la reproducción:**

1. En menú Producción dar click en ABM No Consumibles
2. Click en el botón "Agregar"
3. Completar los campos requeridos
4. Click en botón "Guardar"

![ABM-NCSM01](https://user-images.githubusercontent.com/88331456/138336161-3fb3b6a0-9d67-4f8d-ac5c-19a65c99bc75.png)

**Comment by aalfaro-trazalog** [comment]
Nota 3/12  v1.5.30.3: La columna de lotes no trae datos.

**Comment by floto-trazalog** [comment]
Ambiente: Test - v1.5.30.4

**Sugerencia:**
Se recomienda agregar la Fecha de Inicio para que valide la Fecha de Vencimiento. 
(Al final se adjunta una imagen con una validación similar)

![Valid-Formula](https://user-images.githubusercontent.com/88331456/145453822-717d9e30-be40-4e0f-b457-7b6b87f369aa.png)


Algo similar a esta pantalla
![Valid-Formula2](https://user-images.githubusercontent.com/88331456/145459988-401bb940-c703-42a3-be2a-74031dc05dfc.png)

**Comment by smustafa-trazalog** [comment]
SIN RESOLVER 

![image](https://user-images.githubusercontent.com/98842352/157094688-83c83060-d7bc-43a7-9652-866366951e47.png)

**Comment by floto-trazalog** [comment]
Solucionado en v2.1.7.8.1
