### ISSUE TITLE
Producción -->Producción de Lotes: agregar modal de confirmación

### ISSUE THREAD

**Issue by aalfaro-trazalog** [Trazalog/traz-prod-trazasoft#74]
v.1.5.23
**Descripción:**
Falta agregar un modal de confirmación luego de presionar "Iniciar Etapa", pareciera ser un error porque luego de realizada esa acción no redirige hacia otra pantalla y si se presiona nuevamente el botón, ahí es cuando aparece el cartel de "Unificar Lotes" y si se da ok ocurre el error.

![image](https://user-images.githubusercontent.com/87376576/139123662-09973f52-e21b-4cd0-ba07-99e583502c44.png)

**Pasos para la reproducción:**

1. En el menú Producción dar click en Producción de Lotes
2. Dar click en el botón " + " y seleccionar una etapa a iniciar
3. Completar los datos requeridos
4. Dar click en el botón Iniciar Etapa

**Comment by smustafa-trazalog** [comment]
Modal de confirmación agregado, pero ocurre otro error.
