### ISSUE TITLE
Reporte --> Producción: no figura en el listado el movimiento del Reporte de Producción

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-prod-trazasoft#76]
v1.5.24
**Descripción:**
Al guardar un "Reporte de Producción" el movimiento figura en Almacenes, ABM Stock pero no figura en el listado del ABM Producción" del Módulo Reportes

_Previamente el usuario realiza el Reporte de Producción en el ABM Producción de Lotes._

https://user-images.githubusercontent.com/88331456/139153211-51726305-a1c0-44a5-800c-733521696def.mp4

**Pasos para visualizar el movimiento en módulo Reportes:**

1.  En el menú Reportes
2. Dar click en la pestaña "Producción"
3. Buscar el movimiento del reporte a observar

**Comment by aalfaro-trazalog** [comment]
En la versión 1.5.34 sigue sin funcionar

**Comment by smustafa-trazalog** [comment]
SIN RESOLVER

![image](https://user-images.githubusercontent.com/98842352/157107180-dacc6ef2-0592-4300-9114-edf18bb253c8.png)

**Comment by floto-trazalog** [comment]
Solucionado antes de la v2.1
