### ISSUE TITLE
Logística: agregar buttom "Buscar" en las pantallas de camiones

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-prod-trazasoft#82]
Agro Allium

**Descripción:**
En algunos dispositivos la tecla "Enter" no tiene funcionalidad entonces el sistema no trae los datos del camión y por ende tampoco los de la carga.
Agregar un buttom "Buscar" al lado del campo "Patente" (indicado en la _**Imagen **_), en las siguientes pantallas del Módulo Logística:

- Entrada | Recepción --> Recepción MP
- Descarga Camión
- Salida Camión

_**Imagen 1**_

![AAA-2](https://user-images.githubusercontent.com/88331456/140082088-e2f1908f-efe0-4821-8c5c-42466c07425a.png)

**Pasos para la reproducción:**

1. En módulo Logística
2. Dar click en ABM Entrada | Recepción / _Descarga Camión_ / _Salida Camión_

Puede ser el buttom similar al de la siguiente imagen, el cual se encuentra en el Módulo Almacenes
![image](https://user-images.githubusercontent.com/88331456/140084977-b304c4db-543e-4e08-8cda-27d4d03098df.png)

**Comment by aalfaro-trazalog** [comment]
Además es poco intuitivo para el usuario, porque el sistema no indica en ninguna parte que se debe apretar el enter para que aparezcan los datos precargados. Con el botón de lupa podría solucionarse este inconveniente para todos los dispositivos.

**Comment by aalfaro-trazalog** [comment]
En v 1.5.33.3 (última a fecha 27/01/22) no está implementado este cambio. Volver a colocar componente.
