### ISSUE TITLE
Logística--> Entrada | Recepción--> Entrada: marca error de campo cuando se agrega correctamente y falta modal de confirmación

### ISSUE THREAD

**Issue by floto-trazalog** [Trazalog/traz-prod-trazasoft#97]
### Actualizado 5/09/22
Adicionalmente a lo reportado, en la v 2.1.3 en ambiente PROD MILLENIUM ocurre que no se muestra el modal de confirmación 
![image](https://user-images.githubusercontent.com/87376576/188481490-6aa31e3f-dc74-4bf0-aa7e-783fb04b6e2e.png)

Ambiente Test 
**Sugerencia:**
Al ingresar un camión, el sistema guarda el movimiento, sin embargo el formulario pide completar el campo "Trasportista" cuando los datos fueron cargados correctamente, eso puede confundir al usuario

![agregaPIDEtransp](https://user-images.githubusercontent.com/88331456/142627794-e581d3e8-a6ef-488c-9b8b-53d512a513d4.png)
Lo óptimo sería que se muestren los campos limpios si el formulario fue cargado con éxito

**Pasos para la reproducción:**

1. En menú Logística
2. Dar click en ABM Entrada | Recepción
3. Dar click en "Entrada"
4. Completar los campos obligatorios
5. Dar click en botón "Guardar"

**Comment by smustafa-trazalog** [comment]
SIGUE EL MISMO ERROR

![image](https://user-images.githubusercontent.com/98842352/157538588-c965d81d-0992-422b-9d2f-cdeb63d06456.png)
